[package]
name = "polyclient-rdbms-common"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
polyclient-core.workspace = true
polyclient-plugin-runtime.workspace = true
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
tokio.workspace = true
