[package]
name = "polyclient-plugin-snowflake"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "polyclient-plugin-snowflake"
path = "src/main.rs"

[dependencies]
polyclient-core.workspace = true
polyclient-rdbms-common.workspace = true
polyclient-plugin-runtime.workspace = true
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
anyhow.workspace = true
snowflake-connector-rs = "1.0"
regex = "1.13.0"
